# Generated by Django 5.0.2 on 2024-03-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_name_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='+9941234567890', max_length=15, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
